#!/usr/bin/env bash

set -eu
exec clojure \
    -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.2"} refactor-nrepl/refactor-nrepl {:mvn/version "2.5.1"} cider/cider-nrepl {:mvn/version "0.26.0"}}}' \
    -m nrepl.cmdline \
    --middleware '["refactor-nrepl.middleware/wrap-refactor", "cider.nrepl/cider-middleware"]'

